include:
  - ${PATH_TO_ROOT_DOCKER_PROJ:?}/shared_sckts.yaml
  - ${PATH_TO_ROOT_DOCKER_PROJ:?}/${PATH_FROM_ROOT_TO_NGINX}/compose.yaml
  - ${PATH_TO_ROOT_DOCKER_PROJ:?}/${PATH_FROM_ROOT_TO_IOCAINE}/compose.yaml
  - ./deployment/anubis/compose.yaml

services:
  file_server:
    container_name: file_server
    extends:
      file: ${PATH_TO_ROOT_DOCKER_PROJ:?}/shared_sckts.yaml
      service: shared_sckts_user
    profiles:
      - ${DOCKER_DEFAULT_PROFILE:?}
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    user: ${DOCKER_NONROOT_USER:?}
    volumes:
      # the file server's, you know, files
      - type: bind
        source: ${SERVED_FILES_DIR}
        target: /files/
      # other host-provided data
      - type: bind
        source: ./data/
        target: /data/
    environment:
      # SYNC: paths inside container
      DUFS_SERVE_PATH: /files/
      DUFS_BIND: ${FILE_SERVER_SCKT:?}
      DUFS_AUTH: "admin:${ADMIN_PASSWORD_HASH:?}@${ADMIN_ONLY_ACCESS:?}|\
                  @/amongus.webp,/public/,/unlisted/"
      DUFS_HIDDEN: ${HIDDEN_FILES:?}
      DUFS_CONFIG: /data/config.yaml
    # dufs' base image has umask 022, which prevents nginx's group from writing to the socket
    # (setting `umask` in dockerfile doesn't work because different shell session?)
    post_start:
      - command: chmod 660 ${FILE_SERVER_SCKT:?}
    depends_on:
      nginx:
        condition: service_healthy
      iocaine:
        condition: service_started
      file_server_anubis:
        condition: service_healthy
