# route `files.anonymousrand.xyz:443` to my file server

# first send requests through anubis
server {
    listen 443 ssl; # managed by Certbot
    server_name files.anonymousrand.xyz;

    access_log /var/log/nginx/file_server_access.log;
    error_log /var/log/nginx/file_server_error.log;

    location / {
        include conf.d/snippets/general_forwarding_headers.func;
        # only set these on first proxying "hop"!
        include conf.d/snippets/inbound_edge_forwarding_headers.func;

        set $anubis_in_loc http://unix:${FILE_SERVER_ANUBIS_IN};
        include conf.d/snippets/anubis.func;
    }

    ssl_certificate /etc/letsencrypt/live/files.anonymousrand.xyz/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/files.anonymousrand.xyz/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    client_max_body_size 1G;
}


# then send traffic that passed anubis through iocaine
server {
    listen unix:${FILE_SERVER_ANUBIS_OUT_SCKT};
    server_name files.anonymousrand.xyz;

    location / {
        include conf.d/snippets/general_forwarding_headers.func;

        set $iocaine_upstream @root;
        include snippets/iocaine.func;
    }

    # finally send traffic that passed iocaine to the upstream
    location @root {
        include conf.d/snippets/general_forwarding_headers.func;

        proxy_pass http://unix:${FILE_SERVER_SCKT};
        proxy_redirect off;
    }

    client_max_body_size 1G;
}


# redirect http requests to https
server {
    listen 80;
    server_name files.anonymousrand.xyz;

    client_max_body_size 1G;

    return 301 https://$host$request_uri;
}
